import { LanguageProvider } from '@/LanguageContext'
import './globals.css'
import { Roboto_Mono } from 'next/font/google'
import Nav from '@/components/Nav'

const roboto_mono = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <LanguageProvider>
      <body className={roboto_mono.className}><Nav />{children}</body>
      </LanguageProvider>
    </html>
  )
}
